from builtins import enumerate, isinstance, len, str, sum
from fpdf import FPDF
import datetime
import os


class FancyReport(FPDF):
    def safe_text(self, text: str):
        """Ensures all text is safe for PDF."""
        if not isinstance(text, str):
            text = str(text)
        return text.encode("latin-1", "replace").decode("latin-1")

    # ------------- HEADER & FOOTER -------------
    def header(self):
        self.set_fill_color(10, 37, 64)
        self.rect(0, 0, 210, 18, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Arial", "B", 14)
        self.cell(0, 10, self.safe_text("CircuitGuard  PCB Defect Analysis Report"), ln=True, align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_fill_color(10, 37, 64)
        self.rect(0, 282, 210, 15, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Arial", "I", 9)
        self.cell(
            0,
            10,
            self.safe_text(
                f"Generated by CircuitGuard AI  Page {self.page_no()} • {datetime.datetime.now().strftime('%d %b %Y, %H:%M')}"
            ),
            align="C",
        )

    # ------------- SECTION TITLE -------------
    def section_title(self, title, color=(0, 100, 200)):
        self.set_fill_color(*color)
        self.set_text_color(255, 255, 255)
        self.set_font("Arial", "B", 12)
        self.cell(0, 8, self.safe_text(f"  {title}"), ln=True, fill=True)
        self.ln(4)

    # ------------- SUMMARY CARDS (CENTERED) -------------
    def add_summary_cards(self, data):
        page_width = self.w - 30
        card_w = 45
        spacing = (page_width - len(data) * card_w) / (len(data) - 1)
        start_x = 15
        y = self.get_y() + 2

        for i, (label, value) in enumerate(data.items()):
            x = start_x + i * (card_w + spacing)
            self.set_xy(x, y)
            self.set_fill_color(242, 248, 255)
            self.set_draw_color(180, 200, 230)
            self.rect(x, y, card_w, 20, "DF")
            self.set_text_color(10, 37, 64)
            self.set_font("Arial", "B", 11)
            self.set_xy(x, y + 5)
            self.multi_cell(card_w, 6, self.safe_text(label), align="C")
            self.set_font("Arial", "", 11)
            self.set_xy(x, y + 12)
            self.multi_cell(card_w, 6, self.safe_text(value), align="C")

        self.ln(25)

    # ------------- DEFECT SUMMARY -------------
    def add_summary_list(self, summary):
        self.set_font("Arial", "", 11)
        self.set_text_color(0)
        if not summary:
            self.cell(0, 8, "No defects detected.", ln=True)
        else:
            for cls, count in summary.items():
                self.cell(0, 8, self.safe_text(f" {cls}: {count}"), ln=True)
        self.ln(8)

    # ------------- IMAGE SECTION -------------
    def add_images(self, annotated_path, heatmap_path):
        self.set_font("Arial", "I", 11)
        self.set_text_color(50)
        y_start = self.get_y()

        if os.path.exists(annotated_path):
            self.image(annotated_path, x=15, y=y_start + 5, w=85)
        if os.path.exists(heatmap_path):
            self.image(heatmap_path, x=110, y=y_start + 5, w=85)
        self.ln(95)

    # ------------- TABLE -------------
    def add_table(self, detections):
        self.set_font("Arial", "B", 11)
        self.set_fill_color(0, 100, 200)
        self.set_text_color(255)
        headers = ["#", "Defect Type", "Confidence (%)", "Coordinates (x, y, w, h)"]
        widths = [10, 45, 35, 100]

        for i, h in enumerate(headers):
            self.cell(widths[i], 8, self.safe_text(h), border=0, align="C", fill=True)
        self.ln()

        self.set_font("Arial", "", 10)
        fill = False
        for i, d in enumerate(detections, 1):
            self.set_fill_color(245, 248, 255) if fill else self.set_fill_color(255)
            self.set_text_color(0)
            coords = f"({d['coords'][0]}, {d['coords'][1]}, {d['coords'][2]}, {d['coords'][3]})"
            self.cell(widths[0], 7, str(i), border=0, align="C", fill=True)
            self.cell(widths[1], 7, self.safe_text(d["class"]), border=0, align="C", fill=True)
            self.cell(widths[2], 7, self.safe_text(f"{d['conf']:.1f}"), border=0, align="C", fill=True)
            self.cell(widths[3], 7, self.safe_text(coords), border=0, align="C", fill=True)
            self.ln()
            fill = not fill
        self.ln(8)


# -------------------------------------------------
#            GENERATE FANCY REPORT
# -------------------------------------------------
def generate_fancy_report(summary, annotated_path, heatmap_path, detections, conf_thresh, min_area, max_area, avg_conf):
    pdf = FancyReport()
    pdf.add_page()

    pdf.section_title("Project Summary")
    pdf.add_summary_cards({
        "Confidence": f"{conf_thresh:.2f}",
        "Area Range": f"{min_area}-{max_area}px",
        "Avg Conf": f"{avg_conf:.2f}%",
        "Defects": str(sum(summary.values()))
    })

    pdf.section_title("Detected Defect Summary")
    pdf.add_summary_list(summary)

    pdf.section_title("Visual Results")
    pdf.add_images(annotated_path, heatmap_path)

    pdf.section_title("Detailed Defect Coordinates")
    pdf.add_table(detections)

    pdf.set_font("Arial", "I", 9)
    pdf.set_text_color(100)
    pdf.cell(0, 10, pdf.safe_text("Generated using CircuitGuard AI  Smart PCB Intelligence by Saurabh Singh"),
              ln=True, align="C")

    out_path = "outputs/final_fancy_report.pdf"
    pdf.output(out_path)
    return out_path
